Cypress.on('uncaught:exception', (err, runnable) => {
  // Retorna "false" para evitar que o Cypress falhe nos testes por erros n√£o tratados
  return false;
});
